export const strings = {
  siteName: { kn: 'Publicwrits', en: 'Publicwrits' },
  tagline: { kn: 'ಸತ್ಯ · ದಾಖಲೆ · ಜನಹಿತ', en: 'Truth · Record · Public Interest' },
  volumeLine: { kn: 'ಸಂಪುಟ ೦೧ · ಸಂಚಿಕೆ ೦೧', en: 'VOL. 01 · ISSUE 01' },
  nav: {
    home: { kn: 'ಮುಖಪುಟ', en: 'Home' },
    politics: { kn: 'ರಾಜಕೀಯ', en: 'Politics' },
    karnataka: { kn: 'ಕರ್ನಾಟಕ', en: 'Karnataka' },
    economy: { kn: 'ಆರ್ಥಿಕತೆ', en: 'Economy' },
    local: { kn: 'ಸ್ಥಳೀಯ ಸುದ್ದಿ', en: 'Local' },
    opinion: { kn: 'ಅಭಿಪ್ರಾಯ', en: 'Opinion' },
  },
  breaking: { kn: 'ತುರ್ತು ಸುದ್ದಿ', en: 'Breaking' },
  docketLabel: { kn: 'ಡಾಕೆಟ್ ಸಂಖ್ಯೆ', en: 'Docket No.' },
  notice: {
    kn: 'ಪಬ್ಲಿಕ್\u200cರಿಟ್ಸ್ ಸ್ವತಂತ್ರ ಹಾಗೂ ಪರಿಶೀಲಿತ ವರದಿಗಳಿಗೆ ಬದ್ಧವಾಗಿದೆ. ಪ್ರತಿ ವರದಿಗೂ ಡಾಕೆಟ್ ಸಂಖ್ಯೆ ಮತ್ತು ಮೂಲ ದಾಖಲೆ ಉಲ್ಲೇಖಿಸಲಾಗುತ್ತದೆ.',
    en: 'Publicwrits is committed to independent, verified reporting. Every story carries a docket number and cites its source record.',
  },
  readMore: { kn: 'ಪೂರ್ಣ ವರದಿ ಓದಿ', en: 'Read full report' },
  backHome: { kn: '← ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ', en: '← Back to homepage' },
  filedUnder: { kn: 'ವಿಭಾಗ', en: 'Filed under' },
  byBureau: { kn: 'ವರದಿ', en: 'Reporting by' },
  publishedOn: { kn: 'ಪ್ರಕಟಣೆ', en: 'Published' },
  relatedStories: { kn: 'ಸಂಬಂಧಿತ ವರದಿಗಳು', en: 'Related dockets' },
  footer: {
    about: { kn: 'ನಮ್ಮ ಬಗ್ಗೆ', en: 'About us' },
    editorialPolicy: { kn: 'ಸಂಪಾದಕೀಯ ನೀತಿ', en: 'Editorial policy' },
    contact: { kn: 'ಸಂಪರ್ಕಿಸಿ', en: 'Contact' },
    sections: { kn: 'ವಿಭಾಗಗಳು', en: 'Sections' },
    masthead: { kn: 'ಮಾಸ್ಟ್\u200cಹೆಡ್', en: 'Masthead' },
    description: {
      kn: 'ಸ್ವತಂತ್ರ ಸುದ್ದಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ದಾಖಲೆ ವರದಿ ಜಾಲ',
      en: 'An independent network for news and public-record reporting',
    },
    rights: { kn: '© ೨೦೨೬ PUBLICWRITS.COM — ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ', en: '© 2026 PUBLICWRITS.COM — ALL RIGHTS RESERVED' },
    registration: { kn: 'PRP ಕಾಯ್ದೆ, 2023 ಅಡಿ ನೋಂದಣಿ (ಬಾಕಿ)', en: 'REGISTERED UNDER PRP ACT, 2023 (PENDING)' },
  },
};
